version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1701
      POSTGRES_DB: discord_acc
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      app-network:
    restart: always

  web:
    build: .
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1701@postgres:5432/discord_acc
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./models:/app/models
      - ./public:/app/public
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      app-network:
    restart: always

volumes:
  postgres_data:
networks:
  app-network: